import { type FormEvent, useEffect, useState } from "react";
import { Link, NavLink, Outlet, useLocation, useNavigate } from "react-router";
import { BarChart3, ChevronDown, FolderKanban, LayoutDashboard, LogOut, Menu, Pencil, Plus, Trash2, Users, X } from "lucide-react";
import logo from "../assets/logo.png";
import { adminApi, type Project, type TeamMember } from "../../lib/adminApi";

const inputClass = "h-10 w-full rounded-lg border border-white/10 bg-[#171f2e] px-3 text-sm text-slate-100 outline-none transition placeholder:text-slate-500 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20";
const labelClass = "mb-1.5 block text-xs font-semibold text-slate-300";

function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) {
  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/45 p-4 backdrop-blur-sm">
    <section className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-white/10 bg-[#101826] p-5 shadow-2xl sm:p-6">
      <div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-bold text-white">{title}</h2><button onClick={onClose} aria-label="Close" className="rounded-lg p-2 text-slate-400 hover:bg-white/10"><X className="h-5 w-5" /></button></div>
      {children}
    </section>
  </div>;
}

function ActionButton({ children, onClick, tone = "light" }: { children: React.ReactNode; onClick: () => void; tone?: "light" | "danger" }) {
  return <button onClick={onClick} className={`rounded-lg p-2 transition ${tone === "danger" ? "text-red-400 hover:bg-red-500/10" : "text-slate-400 hover:bg-white/10 hover:text-blue-400"}`}>{children}</button>;
}

export function AdminLayout() {
  const [open, setOpen] = useState(false);
  const [profileOpen, setProfileOpen] = useState(false);
  const location = useLocation();
  const navigate = useNavigate();
  const user = (() => {
    try {
      return JSON.parse(localStorage.getItem("webmarkio_user") || "{}") as { name?: string; email?: string };
    } catch {
      return {};
    }
  })();
  const name = user.name || "Admin User";
  const logout = () => {
    localStorage.removeItem("webmarkio_auth_token");
    localStorage.removeItem("webmarkio_user");
    navigate("/login");
  };
  const pageTitle = location.pathname.includes("/team") ? "Team Management" : location.pathname.includes("/projects") ? "Project Management" : "Dashboard";
  const nav = [
    { to: "/admin", label: "Dashboard", icon: LayoutDashboard, end: true },
    { to: "/admin/projects", label: "Projects", icon: FolderKanban },
    { to: "/admin/team", label: "Team", icon: Users },
  ];
  const sidebar = <aside className="flex h-full w-64 flex-col border-r border-white/10 bg-[#0d1421]">
    <Link to="#" className="flex h-20 items-center border-b border-white/10 px-5"><img src={logo} alt="Webmarkio" className="h-20 w-44 object-contain" /></Link>
    <nav className="space-y-1 px-3 py-5">{nav.map(({ to, label, icon: Icon, end }) => <NavLink key={to} to={to} end={end} onClick={() => setOpen(false)} className={({ isActive }) => `flex items-center gap-3 rounded-xl px-3.5 py-3 text-sm font-semibold transition ${isActive ? "bg-blue-500/15 text-blue-400" : "text-slate-400 hover:bg-white/5 hover:text-white"}`}><Icon className="h-5 w-5" />{label}</NavLink>)}</nav>
    <div className="mt-auto border-t border-white/10 p-4"><p className="text-xs font-medium text-slate-500">WEBMARKIO ADMIN</p><p className="mt-1 text-sm font-semibold text-slate-300">Management panel</p></div>
  </aside>;
  return <div className="min-h-screen bg-[#080d17] text-slate-100">
    <div className="fixed inset-y-0 left-0 z-50 hidden lg:block">{sidebar}</div>
    {open && <><button onClick={() => setOpen(false)} aria-label="Close sidebar" className="fixed inset-0 z-40 bg-slate-950/35 lg:hidden" /><div className="fixed inset-y-0 left-0 z-50 lg:hidden">{sidebar}</div></>}
    <div className="lg:pl-64"><header className="sticky top-0 z-30 flex h-20 items-center justify-between border-b border-white/10 bg-[#0d1421]/95 px-5 backdrop-blur sm:px-8"><div className="flex items-center gap-4"><button onClick={() => setOpen(true)} className="rounded-lg p-2 text-slate-300 hover:bg-white/10 lg:hidden"><Menu className="h-6 w-6" /></button><div><p className="text-xs font-semibold uppercase tracking-wider text-blue-400">Admin panel</p><h1 className="text-lg font-bold text-white">{pageTitle}</h1></div></div><div className="relative"><button onClick={() => setProfileOpen((value) => !value)} className="flex items-center gap-2 rounded-xl px-2 py-1.5 transition hover:bg-white/5"><span className="hidden text-right sm:block"><span className="block text-sm font-semibold text-white">{name}</span><span className="block text-xs text-slate-400">Administrator</span></span><span className="flex h-10 w-10 items-center justify-center rounded-full bg-gradient-to-br from-blue-500 to-indigo-500 text-sm font-bold text-white">{name.charAt(0).toUpperCase()}</span><ChevronDown className={`h-4 w-4 text-slate-400 transition ${profileOpen ? "rotate-180" : ""}`} /></button>{profileOpen && <div className="absolute right-0 top-full mt-2 w-56 overflow-hidden rounded-xl border border-white/10 bg-[#151e2c] p-1.5 shadow-2xl shadow-black/40"><div className="border-b border-white/10 px-3 py-2.5"><p className="truncate text-sm font-semibold text-white">{name}</p><p className="truncate text-xs text-slate-400">{user.email || "Administrator"}</p></div><button onClick={logout} className="mt-1 flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-left text-sm font-semibold text-red-400 transition hover:bg-red-500/10"><LogOut className="h-4 w-4" />Log out</button></div>}</div></header><main className="p-5 sm:p-8"><Outlet /></main></div>
  </div>;
}

export function AdminDashboard() {
  const [counts, setCounts] = useState({ team: 0, projects: 0 });
  useEffect(() => { Promise.all([adminApi.getTeam(), adminApi.getProjects()]).then(([team, projects]) => setCounts({ team: team.length, projects: projects.length })).catch(() => undefined); }, []);
  const cards = [{ label: "Total Projects", value: counts.projects, icon: FolderKanban, color: "bg-blue-600" }, { label: "Team Members", value: counts.team, icon: Users, color: "bg-violet-600" }];
  return <><div className="mb-8"><h2 className="text-2xl font-bold tracking-tight text-white">Welcome to Webmarkio Admin</h2><p className="mt-1 text-sm text-slate-400">Manage your projects and team members from one place.</p></div><div className="grid gap-5 sm:grid-cols-2">{cards.map(({ label, value, icon: Icon, color }) => <div key={label} className="rounded-2xl border border-white/10 bg-[#101826] p-5 shadow-lg shadow-black/10"><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-slate-400">{label}</p><p className="mt-2 text-3xl font-bold text-white">{value}</p></div><div className={`${color} rounded-xl p-3 text-white`}><Icon className="h-6 w-6" /></div></div></div>)}</div><div className="mt-6 rounded-2xl border border-white/10 bg-[#101826] p-6 shadow-lg shadow-black/10"><BarChart3 className="h-8 w-8 text-blue-400" /><h3 className="mt-4 text-lg font-bold text-white">Quick management</h3><p className="mt-1 text-sm text-slate-400">Use the sidebar to add, update, or delete projects and team members.</p></div></>;
}

const emptyTeam = { name: "", position: "", image: "", facebookLink: "", LinkedInLink: "", whatsappNum: "" };
export function AdminTeamPage() {
  const [members, setMembers] = useState<TeamMember[]>([]); const [editing, setEditing] = useState<TeamMember | null | undefined>(); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); adminApi.getTeam().then(setMembers).catch((e: Error) => setNotice(e.message)).finally(() => setLoading(false)); };
  useEffect(load, []);
  const remove = async (member: TeamMember) => { if (!window.confirm(`Delete ${member.name}?`)) return; try { await adminApi.deleteTeam(member._id); setMembers((all) => all.filter((item) => item._id !== member._id)); setNotice("Team member deleted."); } catch (e) { setNotice((e as Error).message); } };
  return <section><PageIntro title="Team members" subtitle="Add and maintain the people behind Webmarkio." action={() => setEditing(null)} label="Add member" />{notice && <Notice text={notice} onClose={() => setNotice("")} />}<div className="overflow-hidden rounded-2xl border border-white/10 bg-[#101826] shadow-lg shadow-black/10"><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left"><thead className="bg-white/[0.03] text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-4">Member</th><th className="px-5 py-4">Position</th><th className="px-5 py-4">Phone</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody>{loading ? <tr><td colSpan={4} className="px-5 py-8 text-center text-sm text-slate-400">Loading team members…</td></tr> : members.length ? members.map((member) => <tr key={member._id} className="border-t border-white/10"><td className="px-5 py-4"><div className="flex items-center gap-3">{member.image ? <img src={member.image} alt="" className="h-10 w-10 rounded-full object-cover" /> : <div className="flex h-10 w-10 items-center justify-center rounded-full bg-blue-500/15 font-bold text-blue-400">{member.name.charAt(0)}</div>}<span className="font-semibold text-slate-100">{member.name}</span></div></td><td className="px-5 py-4 text-sm text-slate-400">{member.position}</td><td className="px-5 py-4 text-sm text-slate-400">{member.whatsappNum || "—"}</td><td className="px-5 py-4"><div className="flex justify-end"><ActionButton onClick={() => setEditing(member)}><Pencil className="h-4 w-4" /></ActionButton><ActionButton onClick={() => remove(member)} tone="danger"><Trash2 className="h-4 w-4" /></ActionButton></div></td></tr>) : <tr><td colSpan={4} className="px-5 py-10 text-center text-sm text-slate-400">No team members yet.</td></tr>}</tbody></table></div></div>{editing !== undefined && <TeamForm member={editing} onClose={() => setEditing(undefined)} onSaved={(member) => { setMembers((all) => editing ? all.map((item) => item._id === member._id ? member : item) : [member, ...all]); setEditing(undefined); setNotice(editing ? "Team member updated." : "Team member added."); }} />}</section>;
}

function TeamForm({ member, onClose, onSaved }: { member: TeamMember | null; onClose: () => void; onSaved: (member: TeamMember) => void }) { const [form, setForm] = useState(member ? { ...member } : emptyTeam); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const update = (key: keyof typeof emptyTeam, value: string) => setForm((previous) => ({ ...previous, [key]: value })); const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(""); try { onSaved(member ? await adminApi.updateTeam(member._id, form) : await adminApi.addTeam(form)); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to save member."); } finally { setSaving(false); } }; return <Modal title={member ? "Update team member" : "Add team member"} onClose={onClose}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Field label="Name" value={form.name} onChange={(v) => update("name", v)} required /><Field label="Position" value={form.position} onChange={(v) => update("position", v)} required /><Field label="Image URL" value={form.image} onChange={(v) => update("image", v)} /><Field label="WhatsApp number" value={form.whatsappNum} onChange={(v) => update("whatsappNum", v)} /><Field label="Facebook URL" value={form.facebookLink} onChange={(v) => update("facebookLink", v)} /><Field label="LinkedIn URL" value={form.LinkedInLink} onChange={(v) => update("LinkedInLink", v)} />{error && <p className="text-sm text-red-600 sm:col-span-2">{error}</p>}<FormActions onClose={onClose} saving={saving} /></form></Modal>; }

const emptyProject = { projectname: "", projecttype: "", companyname: "", projectoverview: "", projectlink: "", mainimage: "", technologies: [] as string[] };
export function AdminProjectsPage() {
  const [projects, setProjects] = useState<Project[]>([]); const [editing, setEditing] = useState<Project | null | undefined>(); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); adminApi.getProjects().then(setProjects).catch((e: Error) => setNotice(e.message)).finally(() => setLoading(false)); }; useEffect(load, []);
  const remove = async (project: Project) => { if (!window.confirm(`Delete ${project.projectname}?`)) return; try { await adminApi.deleteProject(project._id); setProjects((all) => all.filter((item) => item._id !== project._id)); setNotice("Project deleted."); } catch (e) { setNotice((e as Error).message); } };
  return <section><PageIntro title="Projects" subtitle="Manage your portfolio projects and their details." action={() => setEditing(null)} label="Add project" />{notice && <Notice text={notice} onClose={() => setNotice("")} />}<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{loading ? <p className="text-sm text-slate-400">Loading projects…</p> : projects.length ? projects.map((project) => <article key={project._id} className="overflow-hidden rounded-2xl border border-white/10 bg-[#101826] shadow-lg shadow-black/10"><div className="h-32 bg-white/[0.03]">{project.mainimage ? <img src={project.mainimage} alt="" className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center bg-gradient-to-br from-blue-500/20 to-violet-500/20"><FolderKanban className="h-9 w-9 text-blue-400" /></div>}</div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-blue-400">{project.projecttype}</p><h3 className="mt-1 font-bold text-white">{project.projectname}</h3></div><div className="flex -mr-2"><ActionButton onClick={() => setEditing(project)}><Pencil className="h-4 w-4" /></ActionButton><ActionButton onClick={() => remove(project)} tone="danger"><Trash2 className="h-4 w-4" /></ActionButton></div></div><p className="mt-2 line-clamp-2 text-sm text-slate-400">{project.companyname || project.projectoverview || "No description added."}</p></div></article>) : <div className="rounded-2xl border border-dashed border-white/15 bg-[#101826] p-10 text-center text-sm text-slate-400">No projects yet. Add your first project.</div>}</div>{editing !== undefined && <ProjectForm project={editing} onClose={() => setEditing(undefined)} onSaved={(project) => { setProjects((all) => editing ? all.map((item) => item._id === project._id ? project : item) : [project, ...all]); setEditing(undefined); setNotice(editing ? "Project updated." : "Project added."); }} />}</section>;
}

function ProjectForm({ project, onClose, onSaved }: { project: Project | null; onClose: () => void; onSaved: (project: Project) => void }) { const [form, setForm] = useState(project ? { ...project } : emptyProject); const [technologies, setTechnologies] = useState(form.technologies.join(", ")); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const update = (key: Exclude<keyof typeof emptyProject, "technologies">, value: string) => setForm((previous) => ({ ...previous, [key]: value })); const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(""); const payload = { ...form, technologies: technologies.split(",").map((item) => item.trim()).filter(Boolean) }; try { onSaved(project ? await adminApi.updateProject(project._id, payload) : await adminApi.addProject(payload)); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to save project."); } finally { setSaving(false); } }; return <Modal title={project ? "Update project" : "Add project"} onClose={onClose}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Field label="Project name" value={form.projectname} onChange={(v) => update("projectname", v)} required /><Field label="Project type" value={form.projecttype} onChange={(v) => update("projecttype", v)} required /><Field label="Company name" value={form.companyname} onChange={(v) => update("companyname", v)} /><Field label="Project link" value={form.projectlink} onChange={(v) => update("projectlink", v)} /><Field label="Main image URL" value={form.mainimage} onChange={(v) => update("mainimage", v)} /><Field label="Technologies (comma separated)" value={technologies} onChange={setTechnologies} /><div className="sm:col-span-2"><label className={labelClass}>Project overview</label><textarea value={form.projectoverview} onChange={(e) => update("projectoverview", e.target.value)} className={`${inputClass} h-24 py-2`} placeholder="Brief project description" /></div>{error && <p className="text-sm text-red-600 sm:col-span-2">{error}</p>}<FormActions onClose={onClose} saving={saving} /></form></Modal>; }

function PageIntro({ title, subtitle, action, label }: { title: string; subtitle: string; action: () => void; label: string }) { return <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-bold tracking-tight text-white">{title}</h2><p className="mt-1 text-sm text-slate-400">{subtitle}</p></div><button onClick={action} className="inline-flex h-10 items-center gap-2 rounded-lg bg-blue-600 px-4 text-sm font-semibold text-white shadow-lg shadow-blue-900/30 transition hover:bg-blue-500"><Plus className="h-4 w-4" />{label}</button></div>; }
function Notice({ text, onClose }: { text: string; onClose: () => void }) { return <div className="mb-5 flex items-center justify-between rounded-xl border border-blue-400/20 bg-blue-500/10 px-4 py-3 text-sm text-blue-200"><span>{text}</span><button onClick={onClose}><X className="h-4 w-4" /></button></div>; }
function Field({ label, value, onChange, required = false }: { label: string; value: string; onChange: (value: string) => void; required?: boolean }) { return <div><label className={labelClass}>{label}</label><input required={required} value={value} onChange={(event) => onChange(event.target.value)} className={inputClass} /></div>; }
function FormActions({ onClose, saving }: { onClose: () => void; saving: boolean }) { return <div className="flex justify-end gap-3 pt-2 sm:col-span-2"><button type="button" onClick={onClose} className="h-10 rounded-lg border border-white/10 px-4 text-sm font-semibold text-slate-300 hover:bg-white/5">Cancel</button><button disabled={saving} className="h-10 rounded-lg bg-blue-600 px-4 text-sm font-semibold text-white hover:bg-blue-500 disabled:opacity-60">{saving ? "Saving…" : "Save changes"}</button></div>; }
